---
  - name: Playbook for user management
    hosts: web
    tasks:
      - name: User management
        become: True
        become_user: root
        ansible.builtin.user:
          name: "{{ item.name }}"
          home: "{{ item.home | default(('/' if item.name == 'root' else '/home/') + item.name) }}"
          uid: "{{ item.uid }}"
          group: "{{ item.group | default(omit) }}"
          groups: "{{ item.groups | default(omit) }}"
          append: "{{ yes if item.groups is defined | default(omit) }}"
          remove: yes
        loop: "{{ users }}"
